=== ErofeevAS/itacademy/src/com/gmail/erofeev/st/alexei/homework20/stock.xsd
<?xml version ="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.it-academy.by"
           xmlns="http://www.it-academy.by"
           elementFormDefault="qualified">

    <xs:element name="stock" type="fullstock"/>


    <xs:simpleType name="shortstring">
        <xs:restriction base="xs:string">
            <xs:minExclusive value="10"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="category">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="desc" type="shortstring"/>
        </xs:sequence>
        <xs:attribute name="categoryid" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="stockdailyrecord">
        <xs:sequence>
            <xs:element name="priceopen" type="xs:float"/>
            <xs:element name="priceclose" type="xs:float"/>
            <xs:element name="pricechange" type="xs:float"/>
            <xs:element name="volume" type="xs:long"/>
            <xs:element name="date" type="xs:date"/>
        </xs:sequence>
        <xs:attribute name="recordid" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="stockdailyrecordslist">
        <xs:sequence>
            <xs:element name="stockdailyrecord" type="stockdailyrecord" minOccurs="2" maxOccurs="20"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="fullstock">
        <xs:sequence>
            <xs:element name="stockid" type="xs:integer"/>
            <xs:element name="stockcode" type="xs:string"/>
            <xs:element name="stockname" type="xs:string"/>
            <xs:element name="stockdailyrecords" type="stockdailyrecordslist"/>
            <xs:element name="category" type="category"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== ErofeevAS/itacademy/src/com/gmail/erofeev/st/alexei/homework20/stock.xml
<?xml version="1.0"?>
<stock xmlns="http://www.it-academy.by"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.it-academy.by stock.xsd">
    <stockid>666</stockid>
    <stockcode>music store code</stockcode>
    <stockname>music store</stockname>

    <stockdailyrecords>
        <stockdailyrecord recordid="1">
            <priceopen>15</priceopen>
            <priceclose>16</priceclose>
            <pricechange>4</pricechange>
            <volume>1</volume>
            <date>2014-10-12</date>
        </stockdailyrecord>
        <stockdailyrecord recordid="2">
            <priceopen>2</priceopen>
            <priceclose>3</priceclose>
            <pricechange>4</pricechange>
            <volume>5</volume>
            <date>2012-12-12</date>
        </stockdailyrecord>
    </stockdailyrecords>

    <category categoryid="25">
        <name>rock</name>
        <desc>unknown</desc>
    </category>


</stock>
