=== ErofeevAS/itacademy/src/com/gmail/erofeev/st/alexei/controlTwo/files/PurchaseOrder.xsd
<?xml version ="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.it-academy.by"
           xmlns="http://www.it-academy.by"
           elementFormDefault="qualified">
    <xs:element name="PurchaseOrder" type="PurchaseOrder"/>

    <xs:complexType name="PurchaseOrder">
        <xs:sequence>
            <xs:element name="item" type="item" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="OrderDate" type="xs:string"/>
    </xs:complexType>

    <xs:complexType name="item">
        <xs:all>
            <xs:element name="ProductName" type="xs:string"/>
            <xs:element name="Quantity" type="xs:int"/>
            <xs:element name="USPrice" type="xs:float"/>
            <xs:element name="ShipDate" type="xs:string"  minOccurs="0" />
            <xs:element name="Comment" type="xs:string"  minOccurs="0" />
        </xs:all>
        <xs:attribute name="PartNumber" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== ErofeevAS/itacademy/src/com/gmail/erofeev/st/alexei/controlTwo/files/PurchaseOrder.xml
<?xml version="1.0"?>
<PurchaseOrder OrderDate="1999-10-20"
               xmlns="http://www.it-academy.by"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://www.it-academy.by PurchaseOrder.xsd">
    <item PartNumber = "872-AA">
        <ProductName>Lawnmower</ProductName>
        <Quantity>1</Quantity>
        <USPrice>148</USPrice>
        <Comment>Confirm this is electric</Comment>
    </item>
    <item PartNumber = "926-AA">
        <ProductName>Baby monitor</ProductName>
        <Quantity>2</Quantity>
        <USPrice>39.9</USPrice>
        <ShipDate>1999-05-21</ShipDate>
    </item>

</PurchaseOrder>
